### ISSUE TITLE
AppSync and Apollo instead of amplify for graphql

### ISSUE THREAD

**Issue by romainquellec** [CuistotduCoin/cuistot#109]
AppSync and Apollo for two reasons : cache & optimistic update (offline support option).

**Comment by romainquellec** [comment]
https://github.com/jaredpalmer/after.js (Apollo part)

**Comment by stephme** [comment]
TO DO : 
- [ ] Amplify is still use for some operations (search graphqlOperation in the project). Not a major issue since it works this way for now but it could be nice to use apollo here too. To do so, find a way to move withData code into _app in order to be able to import apollo graphl operations utilities where needed. For the operation in AppContainer, we might be forced to move the code elsewhere.
